package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

/**
 * Bien generated by hbm2java
 */
public class Bien implements java.io.Serializable {

    private int codigo;
    private Poliza poliza;
    private Empleado empleado;
    private String identificador;
    private String descripcion;

    public Bien() {
    }

    public Bien(int codigo, Poliza poliza, Empleado empleado, String identificador) {
        this.codigo = codigo;
        this.poliza = poliza;
        this.empleado = empleado;
        this.identificador = identificador;
    }

    public Bien(int codigo, Poliza poliza, Empleado empleado, String identificador, String descripcion) {
        this.codigo = codigo;
        this.poliza = poliza;
        this.empleado = empleado;
        this.identificador = identificador;
        this.descripcion = descripcion;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public Poliza getPoliza() {
        return this.poliza;
    }

    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public String getIdentificador() {
        return this.identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
