package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

/**
 * Cobertura generated by hbm2java
 */
public class Cobertura implements java.io.Serializable {

    private int codigo;
    private String nombre;
    private String descripcion;

    public Cobertura() {
    }

    public Cobertura(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Cobertura(int codigo, String nombre, String descripcion) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
