package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

/**
 * Documentos generated by hbm2java
 */
public class Documentos implements java.io.Serializable {

    private int codigo;
    private Poliza poliza;
    private byte[] contenido;
    private String descripcion;

    public Documentos() {
    }

    public Documentos(int codigo, Poliza poliza, byte[] contenido) {
        this.codigo = codigo;
        this.poliza = poliza;
        this.contenido = contenido;
    }

    public Documentos(int codigo, Poliza poliza, byte[] contenido, String descripcion) {
        this.codigo = codigo;
        this.poliza = poliza;
        this.contenido = contenido;
        this.descripcion = descripcion;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public Poliza getPoliza() {
        return this.poliza;
    }

    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }

    public byte[] getContenido() {
        return this.contenido;
    }

    public void setContenido(byte[] contenido) {
        this.contenido = contenido;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
