package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

    private int id;
    private Departamento departamento;
    private String nombre;
    private String codigo;
    private Set polizas = new HashSet(0);
    private Set biens = new HashSet(0);

    public Empleado() {
    }

    public Empleado(int id, Departamento departamento, String nombre, String codigo) {
        this.id = id;
        this.departamento = departamento;
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public Empleado(int id, Departamento departamento, String nombre, String codigo, Set polizas, Set biens) {
        this.id = id;
        this.departamento = departamento;
        this.nombre = nombre;
        this.codigo = codigo;
        this.polizas = polizas;
        this.biens = biens;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Set getPolizas() {
        return this.polizas;
    }

    public void setPolizas(Set polizas) {
        this.polizas = polizas;
    }

    public Set getBiens() {
        return this.biens;
    }

    public void setBiens(Set biens) {
        this.biens = biens;
    }
}
