package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

    private int codigo;
    private String nombre;
    private String descripcion;
    private Set polizas = new HashSet(0);

    public Estado() {
    }

    public Estado(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Estado(int codigo, String nombre, String descripcion, Set polizas) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.polizas = polizas;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getPolizas() {
        return this.polizas;
    }

    public void setPolizas(Set polizas) {
        this.polizas = polizas;
    }
}
