package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda implements java.io.Serializable {

    private int codigo;
    private String nombre;
    private Set polizas = new HashSet(0);

    public Moneda() {
    }

    public Moneda(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Moneda(int codigo, String nombre, Set polizas) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.polizas = polizas;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getPolizas() {
        return this.polizas;
    }

    public void setPolizas(Set polizas) {
        this.polizas = polizas;
    }
}
