package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Operador generated by hbm2java
 */
public class Operador implements java.io.Serializable {

    private int id;
    private String codigo;
    private String nombre;
    private Set polizas = new HashSet(0);

    public Operador() {
    }

    public Operador(int id, String codigo) {
        this.id = id;
        this.codigo = codigo;
    }

    public Operador(int id, String codigo, String nombre, Set polizas) {
        this.id = id;
        this.codigo = codigo;
        this.nombre = nombre;
        this.polizas = polizas;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getPolizas() {
        return this.polizas;
    }

    public void setPolizas(Set polizas) {
        this.polizas = polizas;
    }
}
