package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago implements java.io.Serializable {

    private int codigo;
    private String nombre;
    private Set pagoses = new HashSet(0);

    public Tipopago() {
    }

    public Tipopago(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Tipopago(int codigo, String nombre, Set pagoses) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.pagoses = pagoses;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getPagoses() {
        return this.pagoses;
    }

    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
}
