package Entidades;
// Generated Apr 25, 2015 12:53:34 AM by Hibernate Tools 3.2.1.GA

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int codigo;
    private String nickname;
    private String contrasena;

    public Usuario() {
    }

    public Usuario(int codigo, String nickname, String contrasena) {
        this.codigo = codigo;
        this.nickname = nickname;
        this.contrasena = contrasena;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
}
